---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      volumes:
      - name: secret-cert-crt
        secret:
          secretName: traefik-cert-crt
      - name: secret-cert-key
        secret:
          secretName: traefik-cert-key
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - image: traefik:v1.7
        name: traefik-ingress-lb
        volumeMounts:
        - mountPath: "/secret/cert.crt"
          name: secret-cert-crt
          subPath: cert.crt
        - mountPath: "/secret/cert.key"
          name: secret-cert-key
          subPath: cert.key
        - mountPath: "/config"
          name: config
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: traefik
          containerPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
          - --api
          - --kubernetes
          - --configfile=/config/traefik.toml
          - --logLevel=INFO
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: traefik
